# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'testPod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Mediatom
  pod 'MediatomiOS'

  # 以下按需导入
  
  # 穿山甲
  pod 'MediatomiOS/SFAdCsjAdapter'
  
  # 优量汇
  pod 'MediatomiOS/SFAdGdtAdapter'
  
  # 快手联盟
  pod 'MediatomiOS/SFAdKsAdapter'
  
  # 百青藤
  pod 'MediatomiOS/SFAdBaiduAdapter'
  
  # 京准通
  pod 'MediatomiOS/SFAdJztAdapter'
  
  # GroMore
  pod 'MediatomiOS/SFAdGromoreAdapter'
  
  # Beizi
  # pod 'MediatomiOS/SFAdBeiziAdapter'
  
  # Meishu
  # pod 'MediatomiOS/SFAdMsAdapter'
  
  # Sigmob
  # pod 'MediatomiOS/SFAdSigmobAdapter'
  
  # Mintegral
  # pod 'MediatomiOS/SFAdMtgAdapter'
  
  # Pangle
  # pod 'MediatomiOS/SFAdPangleAdapter'
  
  # AdMob
  # pod 'MediatomiOS/SFAdMobAdapter'
  
  # Meta
  # pod 'MediatomiOS/SFAdMetaAdapter'
  
  # Vungle
  # pod 'MediatomiOS/SFAdVungleAdapter'
  
  # Tanx
  # pod 'MediatomiOS/SFAdTbAdapter'
  
  # UnityAds
  # pod 'MediatomiOS/SFAdUnityAdapter'
  
  # TopOn
  # pod 'MediatomiOS/SFAdTopOnAdapter'

end
